import { User } from "./user";
import { StrategicApproach } from "./strategic-approach";
import { Area } from "./area";
import { Program } from "./program";
import { Priority } from "./priority";
import { Typification } from "./typification";
import { Management } from "./management";
import { StateByPhase } from "./state-by-phase";
import { Stage } from "./stage";

export class Project {
    id?: number;
    strategic_approach_id?: number;
    strategic_approach?: StrategicApproach;
    area_id?: number;
    area?: Area;
    program_id?: number;
    program?: Program;
    priority_id?: number;
    priority?: Priority;
    typification_id?: number;
    typification?: Typification ;
    functional_lead?: User;
    functional_lead_id?: number;
    management_id?:number;
    management?: Management;
    pmo_id?: number;
    pmo?: User;
    pmo_assitant_id?: number;
    pmo_assitant?: User;
    states_by_phase_id?: number;
    states_by_phase?: StateByPhase;
    pmo_assitant_stage_id?: number;
    pmo_assitant_stage?: Stage;
    title!: string;
    description!: string;
    reception_date!: string;
    pmo_hours!: number;
    pmo_minutes!: number;
    pmo_assistant_hours?: number;
    pmo_assistant_minutes?: number;
    budget_approved!: number;
    budget_executed!: number;
    start_date?: string;
    due_date?: string;
    control_date?: string;
    sprint!: number;
    evaluation?: string;
    test_log!: boolean;
    is_active?: boolean;
    is_delete?: boolean;
    user_creates_id?: User | number;
    user_deletes_id?: User | number;
    user_updates_id?: User | number;
    created_at?: string;
    updated_at?: string;
    deleted_at?: string;

}
